// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherDetailsWebAPI.Models;

namespace WeatherDetailsWebAPI.Migrations
{
    [DbContext(typeof(WeatherDetailsOfCityDbContext))]
    partial class WeatherDetailsOfCityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherDetailsWebAPI.Models.WeatherDetailsOfCity", b =>
                {
                    b.Property<string>("city")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("forecast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("highTemp")
                        .HasColumnType("float");

                    b.Property<double>("lowTemp")
                        .HasColumnType("float");

                    b.HasKey("city");

                    b.ToTable("weathers");
                });
#pragma warning restore 612, 618
        }
    }
}
